org: nfdenuzzo
app: orders-pwa
service: pwa-orders

custom:
  serverless-offline:
    useChildProcesses: true
  dotenv:
    basePath: ./config/

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  memorySize: 512
  timeout: 30

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            enabled: true
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            enabled: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
